[WIP] Markup for header section
franiakat/hello-colors-agency pull request #1
Opened 2018-12-31 14:05 UTC by franiakat

2019-01-03 11:26 UTC, szynszyliszys requested changes

2019-01-03 11:26 UTC, szynszyliszys commented on index.html
> +<html>
You are missing a lang attribute. Add `lang="en"` to your `html` tag.

2019-01-03 11:26 UTC, szynszyliszys commented on index.html
> +          <li>the offer</li>
Hm these look as if tehy could be linking to the sections of the page but they don't really match what is there. Anyway, empty `<a href="/">` tags could be added as obviously these are links and styling will be more challenging then ;)

2019-01-03 11:26 UTC, szynszyliszys commented on index.html
> +            <br/>Creating projects for clients all over the world
I am not a fan of using `<br/>` tag. I would say that this whole span could be a `<p>` with two `<span>` elements inside it. Same in the next sections.

2019-01-03 11:26 UTC, szynszyliszys commented on index.html
> +</html>
Good job 🎉  😄

2019-01-03 11:26 UTC, szynszyliszys commented on index.html
> +    <button>scroll down to find out more about our studio</button>
In my opinion it would work better as a link (it will let you use anchor tag later to scroll down to the section of a page).

2019-01-04 08:32 UTC, franiakat commented on index.html
> +          <li>the offer</li>
Sure, it supposed to be the navigation! 😅

2019-01-04 09:53 UTC, szynszyliszys approved these changes
🎉

2019-01-04 13:26 UTC, merged