Markup for works section
franiakat/hello-colors-agency pull request #2
Opened 2019-01-02 09:02 UTC by franiakat

2019-01-03 13:00 UTC, szynszyliszys requested changes
🥇 😄

2019-01-03 13:00 UTC, szynszyliszys commented on index.html
> +    <section clas="works">
Typo, `clas`

2019-01-03 13:00 UTC, szynszyliszys commented on index.html
> +            <p>
I would put `span`s around Period and Team elements. It will let us break this up later. Also would skip the `<br/>` tag and just let the text wrap along with the size of the container in Team.

2019-01-03 13:00 UTC, szynszyliszys commented on index.html
> +            <a>VISIT THE WEBSITE</a>
If you use <a> tag, it always needs `href` attribute (even if only z`href="/"`). It makes sure that the link is discoverable when using tabs to navigate.

2019-01-03 13:00 UTC, szynszyliszys commented on index.html
> +          <h4>branding & web</h4>
I feel that this is not a header. Each section has a marker of what kind of work was done in the project by an agency and it feels more like a [`<strong>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/strong) element to me. Also I am wondering if it could be in the markup before the name of the project? I would be read as: "branding & web. pineapp." then.

2019-01-03 13:00 UTC, szynszyliszys commented on index.html
> +            <a>VISIT THE WEBSITE</a>
It applies to all sections ;)

2019-01-03 13:00 UTC, szynszyliszys commented on index.html
> +          <h4>branding & web</h4>
It applies to all sections ;)

2019-01-04 09:00 UTC, franiakat commented on index.html
> +          <h4>branding & web</h4>
Actually in the beginning I placed this tag before the name. :) I'll replace that.

2019-01-04 09:51 UTC, szynszyliszys approved these changes
🎉

2019-01-04 09:52 UTC, szynszyliszys commented
Just a nitpick: there is all-caps text, could be changed to lower case (and we will make it uppercase with CSS later).

2019-01-04 13:26 UTC, franiakat commented
I updated this uppercase text, woohoo, merging 🎉

2019-01-04 13:27 UTC, merged