Add markup for Team section
franiakat/hello-colors-agency pull request #3
Opened 2019-01-02 09:19 UTC by franiakat

2019-01-03 13:28 UTC, szynszyliszys requested changes
🎉  just a few small changes 😄

2019-01-03 13:28 UTC, szynszyliszys commented on index.html
> +        <!-- Add photo as a background image of this div -->
This is a meaningful picture so it actually should be added with an `<img>` tag 😄 You can use [figure with figcaption](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/figure) for that.

2019-01-03 13:28 UTC, szynszyliszys commented on index.html
> +        <h5>Next level iceland blue bottle fingerstache:</h5>
It also doesn't feel like header because it has colon at the end. I think it is just emphasized list starter. `<strong` could be a good choice here. If there was a case for a header, it would be `<h4>` because before we used it in another section and it naturally comes after this `<h3>` header at the top of section.

2019-01-03 13:28 UTC, szynszyliszys commented on index.html
> +      <section class="team-description">
I think this is just a `div`, not a `section`. Inside a `.team` section we have a picture and a description and this element here is just to group text to enable styling soon.

2019-01-04 09:10 UTC, franiakat commented on index.html
> +        <!-- Add photo as a background image of this div -->
This is an awesome idea! 🎉

2019-01-04 09:22 UTC, franiakat commented on index.html
> +        <h5>Next level iceland blue bottle fingerstache:</h5>
Oh yeah, that's right :)

2019-01-04 09:49 UTC, szynszyliszys approved these changes
🎉

2019-01-04 13:28 UTC, merged